### ISSUE TITLE
How to fix imbalanced dataset in tangram

### ISSUE THREAD

**Issue by iamharikrishnank** [tangramdotdev/tangram#72] opened 2021-11-23 17:42 UTC
Our dataset is imbalanced.Some values are greater in number compared to majority values in dataset. How can it be solved while creating model in tangram using custom configuration

**Comment by isabella** [comment] 2021-11-23 19:15
Hi @iamharikrishnank:  Currently, Tangram does not automatically handle imbalanced datasets. It is something that we are actively working on, here is the issue to track it: https://github.com/tangramdotdev/tangram/issues/39#issue-992353507.  Here is a discussion where we talk about the best ways to handle this for now: https://github.com/tangramdotdev/tangram/discussions/38. Let me know if you have more questions. Also, if you have a preference of how Tangram will automatically handle imbalanced datasets, let us know!

**Comment by nitsky** [comment] 2022-01-24 19:47
I am going to close this as a duplicate of #39.

**Closed by nitsky** 2022-01-24 19:47 UTC
